---
label: Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: field_group
    name: header
    label: Header Configuration
    fields:
      - type: text
        name: title
        label: Header Title
        description: The title displayed at the top of the page header
        config:
          required: true
      - type: textarea
        name: subtitle
        label: Header Subtitle
        description: The text displayed below the page title
        config:
          wysiwyg: true
          schema:
            format: markdown
      - type: field_group
        name: button
        fields:
          - type: include
            name: include_button
            label: Button
            template: button
  - type: field_group
    name: contact
    label: Contact Configuration
    fields:
      - type: boolean
        name: enabled
        label: Enabled
        description: Displays the contact section below the page content sections
        default: false
      - type: text
        name: title
        label: Section Title
        description: The text displayed at the top of the section
      - type: textarea
        name: subtitle
        label: Section Subtitle
        description: the text displayed below the section title
        config:
          wysiwyg: true
          schema:
            format: markdown
      - type: text
        name: section_id
        label: Section ID
        config:
          required: true
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
      - type: field_group_list
        name: social_links
        label: Social Media Icons
        description: A list of social media icons displayed in the page footer
        config:
          labelField: title
        fields:
          - type: text
            name: title
            label: Icon Title
            config:
              required: true
          - type: text
            name: icon
            label: Icon
            description: Font Awesome icon
            config:
              required: true
          - type: text
            name: link_url
            label: URL
      - type: text
        name: copyright
        label: Copyright Text
        description: The copyright text displayed at the bottom of the page footer
